#!/usr/bin/env python3
from __future__ import annotations

import os
import re
import shlex
import subprocess
from pathlib import Path


def is_valid_openclaw_root(root: Path) -> bool:
    return (root / "dist/extensions/ollama/index.js").exists()


def candidates_from_gateway_status() -> list[Path]:
    try:
        proc = subprocess.run(
            ["openclaw", "gateway", "status"],
            capture_output=True,
            text=True,
            timeout=20,
            check=False,
        )
    except Exception:
        return []

    match = re.search(r"^Command:\s+(.+)$", proc.stdout, flags=re.MULTILINE)
    if not match:
        return []
    cmd = match.group(1).strip()
    try:
        parts = shlex.split(cmd)
    except ValueError:
        parts = cmd.split()
    roots: list[Path] = []
    for part in parts:
        if part.endswith("/dist/entry.js"):
            entry = Path(part)
            roots.append(entry.parent.parent)
    return roots


def resolve_openclaw_root() -> Path:
    raw_env = os.environ.get("OPENCLAW_INSTALL_DIR")
    candidates: list[Path] = []
    if raw_env:
        candidates.append(Path(raw_env))

    candidates.extend(candidates_from_gateway_status())
    candidates.extend(
        [
            Path("/opt/homebrew/lib/node_modules/openclaw"),
            Path("/usr/local/lib/node_modules/openclaw"),
        ]
    )

    for root in candidates:
        if is_valid_openclaw_root(root):
            return root

    raise SystemExit(
        "Unable to locate OpenClaw install root. Set OPENCLAW_INSTALL_DIR and re-run.",
    )


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    generated_dir = repo_root / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)

    root = resolve_openclaw_root()
    bundled_entry = (root / "dist/extensions/ollama/index.js").resolve()

    shim_path = generated_dir / "bundled-ollama-entry.js"
    content = (
        "// Generated by scripts/generate_bundled_shim.py\n"
        "// This file is machine-specific because OpenClaw install paths vary.\n"
        f"import bundledEntry from {bundled_entry.as_posix()!r};\n"
        "export default bundledEntry;\n"
    )
    shim_path.write_text(content)
    (generated_dir / ".last-resolved.txt").write_text(str(bundled_entry) + "\n")

    print(f"Wrote {shim_path}")
    print(f"Resolved bundled entry: {bundled_entry}")


if __name__ == "__main__":
    main()
